spring:
  datasource:
    url: jdbc:mysql://47.104.129.66:3306/bookstore?useSSL=false
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bxia.bookstore.domain
  type-enums-package: com.bxia.bookstore.enums
server:
  port: 8080
  servlet:
    context-path: /bookstore